### ISSUE TITLE
Crash on setValue

### ISSUE THREAD

**Issue by cgarwood** [OpenZWave/qt-openzwave#12]
Getting a crash when trying to setValue on an Aeotec ZWA002 LED bulb. I think it may be related to values with type `Byte` as I am able to setValue on a `Bool` value without a crash.

```
[20200107 1:01:39.969 UTC] [qt.mqtt.connection.verbose] [debug]: Finalize PUBLISH: topic: QMqttTopicName("OpenZWave/1/node/33/statistics/")  payloadLength: 774
[20200107 1:01:44.595 UTC] [qt.mqtt.connection.verbose] [debug]: void QMqttConnection::transportReadReady()
[20200107 1:01:44.595 UTC] [qt.mqtt.connection.verbose] [debug]: Received PUBLISH
[20200107 1:01:44.595 UTC] [qt.mqtt.connection.verbose] [debug]: Finalize PUBLISH: topic: QMqttTopicName("OpenZWave/1/command/setvalue/")  payloadLength: 46
[20200107 1:01:44.595 UTC] [ozw.mqtt.commands] [debug]: Got  "OpenZWave/1/command/setvalue/"  Message:  "{\"ValueIDKey\": 1407375551070225, \"Value\": 255}"
ozwdaemon: /usr/include/rapidjson/document.h:1646: unsigned int rapidjson::GenericValue<Encoding, Allocator>::GetUint() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `data_.f.flags & kUintFlag' failed.
[20200107 1:01:44.597 UTC] [default] [warning]: =============================
[20200107 1:01:44.598 UTC] [default] [warning]: CRASH!!! - Dumping Backtrace:
[20200107 1:01:44.598 UTC] [default] [warning]: =============================
[20200107 1:01:44.598 UTC] [default] [warning]: #1  0x000055d5f88e7502 sp=0x000055d5f8c891e0 dumpCallback(google_breakpad::MinidumpDescriptor const&, void*, bool) + 0x32
[20200107 1:01:44.599 UTC] [default] [warning]: #2  0x000055d5f88fb765 sp=0x000055d5f8c893d0 google_breakpad::ExceptionHandler::GenerateDump(google_breakpad::ExceptionHandler::CrashContext*) + 0x375
[20200107 1:01:44.599 UTC] [default] [warning]: #3  0x000055d5f88fbaaf sp=0x000055d5f8c89470 google_breakpad::ExceptionHandler::SignalHandler(int, siginfo_t*, void*) + 0x9f
[20200107 1:01:44.600 UTC] [default] [warning]: #4  0x00007fa1cdb75520 sp=0x000055d5f8c89540 funlockfile + 0x50
[20200107 1:01:44.600 UTC] [default] [warning]: #5  0x00007fa1cd858081 sp=0x00007ffc82823310 gsignal + 0x141
[20200107 1:01:44.601 UTC] [default] [warning]: #6  0x00007fa1cd843535 sp=0x00007ffc82823430 abort + 0x121
[20200107 1:01:44.601 UTC] [default] [warning]: #7  0x00007fa1cd84340f sp=0x00007ffc82823560 __libc_freeres + 0x121
[20200107 1:01:44.602 UTC] [default] [warning]: #8  0x00007fa1cd850b92 sp=0x00007ffc828235b0 __assert_fail + 0x42
[20200107 1:01:44.602 UTC] [default] [warning]: #9  0x000055d5f88e1733 sp=0x00007ffc828235e0 rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::GetUint() const [clone .isra.0] [clone .part.0] + 0x23
[20200107 1:01:44.602 UTC] [default] [warning]: #10 0x000055d5f88e48e5 sp=0x00007ffc828235f0 MqttCommand_SetValue::processMessage(rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>&) + 0x2f05
[20200107 1:01:44.602 UTC] [default] [warning]: #11 0x000055d5f88d68eb sp=0x00007ffc828237d0 MqttCommand::messageReceived(QMqttMessage) + 0x28eb
[20200107 1:01:44.602 UTC] [default] [warning]: #12 0x000055d5f88d6e39 sp=0x00007ffc82823a40 QtPrivate::QSlotObject<void (MqttCommand::*)(QMqttMessage), QtPrivate::List<QMqttMessage>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) + 0x49
[20200107 1:01:44.603 UTC] [default] [warning]: #13 0x00007fa1cde2a5b8 sp=0x00007ffc82823a70 QMetaObject::activate(QObject*, int, int, void**) + 0x918
[20200107 1:01:44.603 UTC] [default] [warning]: #14 0x00007fa1ce29c1f5 sp=0x00007ffc82823b60 QMqttSubscription::messageReceived(QMqttMessage) + 0x35
[20200107 1:01:44.604 UTC] [default] [warning]: #15 0x00007fa1ce2921b4 sp=0x00007ffc82823b90 QMqttConnection::finalize_publish() + 0x1d4
[20200107 1:01:44.604 UTC] [default] [warning]: #16 0x00007fa1ce292b1f sp=0x00007ffc82823c60 QMqttConnection::processDataHelper() + 0x2bf
[20200107 1:01:44.605 UTC] [default] [warning]: #17 0x00007fa1ce2932a8 sp=0x00007ffc82823cc0 QMqttConnection::transportReadReady() + 0x78
[20200107 1:01:44.605 UTC] [default] [warning]: #18 0x00007fa1cde2a5b8 sp=0x00007ffc82823d30 QMetaObject::activate(QObject*, int, int, void**) + 0x918
[20200107 1:01:44.606 UTC] [default] [warning]: #19 0x00007fa1ce1a5874 sp=0x00007ffc82823e20 QAbstractSocket::setSocketDescriptor(long long, QAbstractSocket::SocketState, QFlags<QIODevice::OpenModeFlag>) + 0x664
[20200107 1:01:44.606 UTC] [default] [warning]: #20 0x00007fa1ce1a590b sp=0x00007ffc82823e40 QAbstractSocket::setSocketDescriptor(long long, QAbstractSocket::SocketState, QFlags<QIODevice::OpenModeFlag>) + 0x6fb
[20200107 1:01:44.607 UTC] [default] [warning]: #21 0x00007fa1ce1b7921 sp=0x00007ffc82823e70 QTcpServer::incomingConnection(long long) + 0xb561
[20200107 1:01:44.607 UTC] [default] [warning]: #22 0x00007fa1cddffaff sp=0x00007ffc82823e80 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 0x15f
[20200107 1:01:44.608 UTC] [default] [warning]: #23 0x00007fa1cde56495 sp=0x00007ffc82823ef0 QEventDispatcherGlib::registerSocketNotifier(QSocketNotifier*) + 0x145
[20200107 1:01:44.608 UTC] [default] [warning]: #24 0x00007fa1ccd3af1d sp=0x00007ffc82823f30 g_main_context_dispatch + 0x27d
[20200107 1:01:44.608 UTC] [default] [warning]: #25 0x00007fa1ccd3b1a0 sp=0x00007ffc82823fb0 g_main_context_dispatch + 0x500
[20200107 1:01:44.609 UTC] [default] [warning]: #26 0x00007fa1ccd3b22f sp=0x00007ffc82824010 g_main_context_iteration + 0x2f
[20200107 1:01:44.609 UTC] [default] [warning]: #27 0x00007fa1cde55891 sp=0x00007ffc82824030 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 0x61
[20200107 1:01:44.610 UTC] [default] [warning]: #28 0x00007fa1cddfe7ab sp=0x00007ffc82824080 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 0x12b
[20200107 1:01:44.610 UTC] [default] [warning]: #29 0x00007fa1cde06252 sp=0x00007ffc82824100 QCoreApplication::exec() + 0x92
[20200107 1:01:44.610 UTC] [default] [warning]: #30 0x000055d5f88a5db3 sp=0x00007ffc82824160 main + 0x25b3
[20200107 1:01:44.611 UTC] [default] [warning]: #31 0x00007fa1cd844bbb sp=0x00007ffc828245f0 __libc_start_main + 0xeb
[20200107 1:01:44.611 UTC] [default] [warning]: #32 0x000055d5f88a6e0a sp=0x00007ffc828246b0 _start + 0x2a
[20200107 1:01:44.611 UTC] [default] [warning]: dumpCallback Succeeded:  false  at  /opt/ozw/config/crashes//db4401ce-3965-424b-34391aac-eb77aae0.dmp
Aborted (core dumped)
```

setValue data sent:
```
{"ValueIDKey": 659128337, "Value": 66}
```

Value data:
```
{
    "Label": "Level",
    "Value": 99,
    "Units": "",
    "Min": 0,
    "Max": 255,
    "Type": "Byte",
    "Instance": 1,
    "CommandClass": "COMMAND_CLASS_SWITCH_MULTILEVEL",
    "Index": 0,
    "Node": 39,
    "Genre": "User",
    "Help": "The Current Level of the Device",
    "ValueIDKey": 659128337,
    "ReadOnly": false,
    "WriteOnly": false,
    "ValueSet": false,
    "ValuePolled": false,
    "ChangeVerified": false,
    "Event": "valueAdded",
    "TimeStamp": 1578358859
}
```

**Comment by Fishwaldo** [comment]
This should be fixed. New Images are building now. 

Could you run your docker with "--security-opt seccomp=unconfined" in the future as this will give more meaningful backtrace dump I can diagnose with...

(I had to search around a bit to find this error)

**Comment by marcelveldt** [comment]
Sorry to chimb in, I'm testing a bit to see if I can help with the development of the new hass component.
Seems like this issue is not yet fixed. Try to set value to  new brightness level on a dimmer and this will result in a crash.

```
20200117 13:12:25.601 CET] [ozw.mqtt.commands] [debug]: Got  "OpenZWave/1/command/setvalue/"  Message:  "{\"ValueIDKey\": 105480209, \"Value\": 71}"
[20200117 13:12:25.601 CET] [ozw.mqtt.commands.setValue] [info]: Setting  105480209  to Value  QVariant(uint, 71)
[20200117 13:12:25.601 CET] [ozw.values] [debug]: setData Called for Row 36  With Value QVariant(uint, 71)
[20200117 13:12:25.601 CET] [ozw.values] [debug]: valueModel Changed! QTOZW_ValueIds::Value - 36 :  QVariant(uint, 71)
[20200117 13:12:25.601 CET] [ozw.values] [debug]: valueModel Changed! vidKey: 105480209 QVariant(uint, 71)
[20200117 13:12:25.601 CET] [ozw.library] [info]: Info - Node: 6 Value::Set - COMMAND_CLASS_SWITCH_MULTILEVEL - Level - 0 - 1 - 71
[20200117 13:12:25.601 CET] [ozw.library] [info]: Info - Node: 6 SwitchMultilevel::Set - Setting to level 71
[20200117 13:12:25.637 CET] [default] [warning]: =============================
[20200117 13:12:25.637 CET] [default] [warning]: CRASH!!! - Dumping Backtrace:
[20200117 13:12:25.637 CET] [default] [warning]: =============================
```

**Comment by marcelveldt** [comment]
@Fishwaldo just in case the docker image was outdated I've build from source and the issue still exists.
It will crash as soon as you try to set the value (integer between 0 and 255)

**Comment by Fishwaldo** [comment]
Thats a separate issue. https://github.com/OpenZWave/open-zwave/issues/1981

After the Interviews are complete (QueryStage_Complete) - Restart the docker image and it shouldn't crash after that.

**Comment by marcelveldt** [comment]
> Thats a separate issue. [OpenZWave/open-zwave#1981](https://github.com/OpenZWave/open-zwave/issues/1981)
> 
> After the Interviews are complete (QueryStage_Complete) - Restart the docker image and it shouldn't crash after that.

Thanks for the reply! How to track the progress ? I have a lot of battery powered sensors, do I have to wait untill all of them are queried ? I had the docker container running for hours and the non-battery devices were all queried.

**Comment by marcelveldt** [comment]
@Fishwaldo sorry to bother you again. Still not getting anywhere with this.
1) When I try to set the brightness value for a fibaro dimmer, this will crash openzwave. The dimmer is in completed state. Toggling switches does work properly (bool values). In fact, everything is working great ad far as I can see. 

2) It seems that the cache with deviceinfo is not written to disk ? At each crash all data for the battery powered devices is lost again and only comes back after a very long time (wake up interval) or when I wake up the device manually. 

I'd like to help out with the development of the python wrapper / new homeassistant implementation and while I've already written some code I can't test it :-)

**Comment by marcelveldt** [comment]
Nevermind, the cachefile was in fact the issue. It wasn't written to disk (docker issue) so the devices specs needed interviewing each start so there was never a chance to reboot with the correct info after fetching the correct details.

**Comment by Fishwaldo** [comment]
Could you explain more about the cache file issue? I’d like to put in checks when booting the image to make sure things like this don’t happen.
