### ISSUE TITLE
refreshnodeinfo strange behaviour

### ISSUE THREAD

**Issue by marcelveldt** [OpenZWave/qt-openzwave#63]
Issuing a refreshnodeinfo command seems to cause a crash of the daemon. 
Tested it a few times on different nodes and in all cases OZW daemon crashed and restarted.

**Comment by Fishwaldo** [comment]
Can you provide a log from the crash? I just tested on a few devices and can't reproduce any crashes - It maybe around specific devices you have etc.

**Comment by uSpike** [comment]
I'm seeing this as well.

```
[20200612 13:30:50.697 CDT] [ozw.library] [info]: Info - Node: 23 Response RTT 127 Average Response RTT 106
[20200612 13:30:50.703 CDT] [ozw.daemon] [warning]: =============================
[20200612 13:30:50.703 CDT] [ozw.daemon] [warning]: CRASH!!! - Dumping Backtrace:
[20200612 13:30:50.703 CDT] [ozw.daemon] [warning]: =============================
[20200612 13:30:50.703 CDT] [ozw.daemon] [warning]: #1  0x000055e2adcec69b sp=0x00007fc75edc0e10 dumpCallback(google_breakpad::MinidumpDescriptor const&, void*, bool) + 0x2b
[20200612 13:30:50.703 CDT] [ozw.daemon] [warning]: #2  0x000055e2add01585 sp=0x00007fc75edc1050 google_breakpad::ExceptionHandler::GenerateDump(google_breakpad::ExceptionHandler::CrashContext*) + 0x375
[20200612 13:30:50.704 CDT] [ozw.daemon] [warning]: #3  0x000055e2add018cf sp=0x00007fc75edc10f0 google_breakpad::ExceptionHandler::SignalHandler(int, siginfo_t*, void*) + 0x9f
[20200612 13:30:50.704 CDT] [ozw.daemon] [warning]: #4  0x00007fc761f14110 sp=0x00007fc75edc11c0 funlockfile + 0x50
[20200612 13:30:50.704 CDT] [ozw.daemon] [warning]: #5  0x00007fc761a92471 sp=0x00007fc75edc1600 OpenZWave::Internal::VC::Value::VerifyRefreshedValue(void*, void*, void*, OpenZWave::ValueID::ValueType, int, int, int) + 0x11
[20200612 13:30:50.704 CDT] [ozw.daemon] [warning]: #6  0x00007fc761a9b9ce sp=0x00007fc75edc1650 OpenZWave::Internal::VC::ValueString::OnValueRefreshed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x2e
[20200612 13:30:50.705 CDT] [ozw.daemon] [warning]: #7  0x00007fc761a47931 sp=0x00007fc75edc1680 OpenZWave::Internal::CC::ManufacturerSpecific::HandleMsg(unsigned char const*, unsigned int, unsigned int) + 0x5d1
[20200612 13:30:50.705 CDT] [ozw.daemon] [warning]: #8  0x00007fc761b09018 sp=0x00007fc75edc1730 OpenZWave::Node::ApplicationCommandHandler(unsigned char const*, bool) + 0x178
[20200612 13:30:50.705 CDT] [ozw.daemon] [warning]: #9  0x00007fc761adaf6b sp=0x00007fc75edc17b0 OpenZWave::Driver::ProcessMsg(unsigned char*, unsigned char) + 0x1fb
[20200612 13:30:50.705 CDT] [ozw.daemon] [warning]: #10 0x00007fc761adc316 sp=0x00007fc75edc1900 OpenZWave::Driver::ReadMsg() + 0x616
[20200612 13:30:50.706 CDT] [ozw.daemon] [warning]: #11 0x00007fc761ade42e sp=0x00007fc75edc1db0 OpenZWave::Driver::DriverThreadProc(OpenZWave::Internal::Platform::Event*) + 0x3ee
[20200612 13:30:50.706 CDT] [ozw.daemon] [warning]: #12 0x00007fc761aa77d3 sp=0x00007fc75edc1ea0 OpenZWave::Internal::Platform::ThreadImpl::Run() + 0x13
[20200612 13:30:50.706 CDT] [ozw.daemon] [warning]: #13 0x00007fc761aa77e9 sp=0x00007fc75edc1eb0 OpenZWave::Internal::Platform::ThreadImpl::ThreadProc(void*) + 0x9
[20200612 13:30:50.706 CDT] [ozw.daemon] [warning]: #14 0x00007fc761f08f27 sp=0x00007fc75edc1ec0 start_thread + 0xd7
[20200612 13:30:50.707 CDT] [ozw.daemon] [warning]: #15 0x00007fc761c6d2ff sp=0x00007fc75edc1f80 clone + 0x3f
[20200612 13:30:50.707 CDT] [ozw.daemon] [warning]: dumpCallback Succeeded:  true  at  /opt/ozw/config/crashes//f57a8a4e-d59c-4d5c-87e2da8b-243e3b52.dmp
[20200612 13:30:50.707 CDT] [ozw.daemon] [warning]: Uploading MiniDump to  https://sentry.io/api/1868130/minidump/?sentry_key=e086ba93030843199aab391947d205da
Failed to open curl lib from binary, use libcurl.so instead
[20200612 13:30:51.035 CDT] [ozw.daemon] [warning]: Uploaded Crash minidump With ID:  a16c6be7-2e04-49b2-8961-586490c9329c
2020-06-12 13:30:52,072 INFO exited: ozwdaemon (terminated by SIGSEGV (core dumped); not expected)
```

Trying to call for schlage BE469 for https://github.com/OpenZWave/open-zwave/pull/2247

**Comment by andrerod** [comment]
I can confirm i see the same behavior. It doesn't seem to be device dependent though (unless that device is the aeotec zwave usb stick) as i observed it with a few different devices.

**Comment by andrerod** [comment]
This problem went away once i moved to ozwdaemon container image provided in docker-hub instead of the one that ships with hassio.

I don't know if the problem got fixed in the last 2/3 weeks (since 0.44 of the hassio container was published), or if it relates to something else, but i can clearly observe a much more stable version now.

One other aspect i changed was moving from running it in a raspberry pi (ARM based) to a NUC (x86 based). Not sure if that would have anything to do with this though.

**Comment by wycodegroot** [comment]
I still have this issue. Tried several times to refresh a node and every time the daemon crashes. 

Log from the crash:
```
[20200707 15:42:13.852 CEST] [ozw.logging] [debug]: popping Log Mesages 
[20200707 15:42:13.908 CEST] [ozw.library] [debug]: Detail - Node: 18 AdvanceQueries queryPending=0 queryRetries=0 queryStage=None live=1 
[20200707 15:42:13.908 CEST] [ozw.logging] [debug]: popping Log Mesages 
[20200707 15:42:13.909 CEST] [ozw.library] [debug]: Detail - Node: 18 QueryStage_ProtocolInfo 
[20200707 15:42:13.909 CEST] [ozw.logging] [debug]: popping Log Mesages 
[20200707 15:42:13.910 CEST] [ozw.library] [debug]: Detail - Node: 18 Queuing (Query) Get Node Protocol Info (Node=18): 0x01, 0x04, 0x00, 0x41, 0x12, 0xa8 
[20200707 15:42:13.910 CEST] [ozw.logging] [debug]: popping Log Mesages 
[20200707 15:42:13.911 CEST] [ozw.library] [debug]: Detail - Node: 18 Queuing (Query) Query Stage Complete (ProtocolInfo) 
[20200707 15:42:13.911 CEST] [ozw.logging] [debug]: popping Log Mesages 
[20200707 15:42:13.912 CEST] [ozw.library] [info]: Info - Node: 18 Initializing Node. New Node: false (false) 
[20200707 15:42:13.912 CEST] [ozw.logging] [debug]: popping Log Mesages 
[20200707 15:42:13.919 CEST] [ozw.library] [debug]: Detail - Node: 18 Queuing (Send) MultiChannel Encapsulated (instance=3): SwitchBinaryCmd_Get (Node=18): 0x01, 0x0d, 0x00, 0x13, 0x12, 0x06, 0x60, 0x0d, 0x01, 0x02, 0x25, 0x02, 0x25, 0xd3, 0x4a 
[20200707 15:42:13.919 CEST] [ozw.logging] [debug]: popping Log Mesages 
[20200707 15:42:13.962 CEST] [ozw.mqtt.commands] [info]: Processed Message for  "refreshnodeinfo" :  "{ \n\"node\": 18\n}" 
[20200707 15:42:13.963 CEST] [ozw.daemon] [warning]: ============================= 
[20200707 15:42:13.964 CEST] [ozw.daemon] [warning]: CRASH!!! - Dumping Backtrace: 
[20200707 15:42:13.964 CEST] [ozw.daemon] [warning]: ============================= 
[20200707 15:42:13.964 CEST] [ozw.daemon] [warning]: #1  0x000055b0bbc442ab sp=0x00007f8821c63b10 dumpCallback(google_breakpad::MinidumpDescriptor const&, void*, bool) + 0x2b 
[20200707 15:42:13.964 CEST] [ozw.daemon] [warning]: #2  0x000055b0bbc598b5 sp=0x00007f8821c63d50 google_breakpad::ExceptionHandler::GenerateDump(google_breakpad::ExceptionHandler::CrashContext*) + 0x375 
[20200707 15:42:13.965 CEST] [ozw.daemon] [warning]: #3  0x000055b0bbc59bff sp=0x00007f8821c63df0 google_breakpad::ExceptionHandler::SignalHandler(int, siginfo_t*, void*) + 0x9f 
[20200707 15:42:13.966 CEST] [ozw.daemon] [warning]: #4  0x00007f8825112110 sp=0x00007f8821c63ec0 funlockfile + 0x50 
[20200707 15:42:13.966 CEST] [ozw.daemon] [warning]: #5  0x00007f8824fecca3 sp=0x00007f8821c64578 std::_Rb_tree_increment(std::_Rb_tree_node_base*) + 0x13 
[20200707 15:42:13.967 CEST] [ozw.daemon] [warning]: #6  0x00007f8824c6a855 sp=0x00007f8821c64580 OpenZWave::Internal::CC::CommandClass::CheckForRefreshValues(OpenZWave::Internal::VC::Value const*) + 0x185 
[20200707 15:42:13.968 CEST] [ozw.daemon] [warning]: #7  0x00007f8824c8d964 sp=0x00007f8821c645f0 OpenZWave::Internal::VC::Value::VerifyRefreshedValue(void*, void*, void*, OpenZWave::ValueID::ValueType, int, int, int) + 0x434 
[20200707 15:42:13.969 CEST] [ozw.daemon] [warning]: #8  0x00007f8824c97949 sp=0x00007f8821c64640 OpenZWave::Internal::VC::ValueBool::OnValueRefreshed(bool) + 0x29 
[20200707 15:42:13.970 CEST] [ozw.daemon] [warning]: #9  0x00007f8824c5a85f sp=0x00007f8821c64670 OpenZWave::Internal::CC::SwitchBinary::HandleMsg(unsigned char const*, unsigned int, unsigned int) + 0x7f 
[20200707 15:42:13.970 CEST] [ozw.daemon] [warning]: #10 0x00007f8824c3f0a3 sp=0x00007f8821c646a0 OpenZWave::Internal::CC::MultiInstance::HandleMultiChannelEncap(unsigned char const*, unsigned int) + 0x123 
[20200707 15:42:13.979 CEST] [ozw.daemon] [warning]: #11 0x00007f8824c4027e sp=0x00007f8821c64710 OpenZWave::Internal::CC::MultiInstance::HandleMsg(unsigned char const*, unsigned int, unsigned int) + 0xfe 
[20200707 15:42:13.981 CEST] [ozw.daemon] [warning]: #12 0x00007f8824d05168 sp=0x00007f8821c64730 OpenZWave::Node::ApplicationCommandHandler(unsigned char const*, bool) + 0x178 
[20200707 15:42:13.981 CEST] [ozw.daemon] [warning]: #13 0x00007f8824cd67db sp=0x00007f8821c647b0 OpenZWave::Driver::ProcessMsg(unsigned char*, unsigned char) + 0x1fb 
[20200707 15:42:13.982 CEST] [ozw.daemon] [warning]: #14 0x00007f8824cd7b96 sp=0x00007f8821c64900 OpenZWave::Driver::ReadMsg() + 0x626 
[20200707 15:42:13.983 CEST] [ozw.daemon] [warning]: #15 0x00007f8824cd9c62 sp=0x00007f8821c64db0 OpenZWave::Driver::DriverThreadProc(OpenZWave::Internal::Platform::Event*) + 0x392 
[20200707 15:42:13.983 CEST] [ozw.daemon] [warning]: #16 0x00007f8824ca2bd3 sp=0x00007f8821c64ea0 OpenZWave::Internal::Platform::ThreadImpl::Run() + 0x13 
[20200707 15:42:13.984 CEST] [ozw.daemon] [warning]: #17 0x00007f8824ca2be9 sp=0x00007f8821c64eb0 OpenZWave::Internal::Platform::ThreadImpl::ThreadProc(void*) + 0x9 
[20200707 15:42:13.985 CEST] [ozw.daemon] [warning]: #18 0x00007f8825106f27 sp=0x00007f8821c64ec0 start_thread + 0xd7 
[20200707 15:42:13.985 CEST] [ozw.daemon] [warning]: #19 0x00007f8824e6b31f sp=0x00007f8821c64f80 clone + 0x3f 
[20200707 15:42:13.985 CEST] [ozw.daemon] [warning]: dumpCallback Succeeded:  true  at  /opt/ozw/config/crashes//bdcd3caa-8bb8-4edb-376df8b3-1f7b0d0d.dmp 
[20200707 15:42:13.985 CEST] [ozw.daemon] [warning]: Uploading MiniDump to  https://sentry.io/api/1868130/minidump/?sentry_key=e086ba93030843199aab391947d205da 
Failed to open curl lib from binary, use libcurl.so instead
[20200707 15:42:18.798 CEST] [ozw.daemon] [warning]: Uploaded Crash minidump With ID:  920e1faf-a8ee-43a0-883b-42f15c68b0d3 
```
